export const MENSAJE_EXITO = "La operación se realizó con éxito";
export const MENSAJE_ERROR = "Ocurrió un error al realizar la operación";
export const MENSAJE_SEGURO = "¿Estás seguro?";
export const MENSAJE_ELIMINAR = "Se procedera a eliminar el registro";
export const MENSAJE_REGISTRADO = "Registrado!";
export const MENSAJE_ACTUALIZADO = "¡Actualizado!";
export const MENSAJE_ELIMINADO = "¡Eliminado!";
export const MENSAJE_NO_AUTORIZADO = "Ud. no se encuentra autorizado comuniquese con un administrador!";
export const MENSAJE_CAMBIO_STATUS = "Actualizado!";
